version: '3.8'

services:
  server:
    container_name: ohol-server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8005:8005'
    networks:
      - ohol
    volumes:
      - ./data:/ohol/data
      - ./settings:/ohol/settings

volumes:
  server:
    driver: local

networks:
  ohol:
    name: ohol
    driver: bridge
