name: Build
on:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout minorGems
        uses: actions/checkout@v4
        with:
          repository: jasonrohrer/minorGems
          path: minorGems

      - name: Checkout OneLifeData7
        uses: actions/checkout@v4
        with:
          repository: jasonrohrer/OneLifeData7
          path: OneLifeData7

      - name: Checkout OneLifeServer
        uses: actions/checkout@v4
        with:
          repository: jasonrohrer/OneLife
          path: OneLife
          ref: refs/tags/OneLife_liveServer

      - name: Install libraries
        run: |
          sudo apt install mingw-w64-common g++-mingw-w64 make git -y

      - name: Compile server
        run: |
          cd OneLife/server
          ./configure 3
          ln -s /usr/x86_64-w64-mingw32/include/winsock.h /usr/x86_64-w64-mingw32/include/Winsock.h
          sed -i 's/windres/i686-w64-mingw32-windres/' /ohol/minorGems/game/platforms/SDL/Makefile.MinGW
          make \
                -e PLATFORM=Win32 \
                -e PLATFORM_PATH=win32 \
                -e TIME_PLATFORM=Win32 \
                -e TIME_PLATFORM_PATH=win32 \
                -e DIRECTORY_PLATFORM=Win32 \
                -e DIRECTORY_PLATFORM_PATH=win32 \
                -e POLL_PLATFORM=Unix \
                -e POLL_PLATFORM_PATH=unix \
                -e GXX="x86_64-w64-mingw32-gcc" \
                -e PLATFORM_LIBJPEG_FLAG="-ljpeg" \
                -e PLATFORM_LIBPNG_FLAG="-lz -lpng" \
                -e PLATFORM_COMPILE_FLAGS="-DWIN_32 -DSTATICLIB" \
                -e PLATFORM_LINK_FLAGS="-lopengl32 -lglu32 -lmingw32 -mwindows -lwsock32 -lwinmm -lstdc++ -static-libstdc++ -static-libgcc ${CUSTOM_MINGW_LINK_FLAGS}" \
                -e PLATFORM_LINK_FLAGS_HEADLESS="-lmingw32 -mconsole -mwindows -lwsock32 -static-libstdc++ -lstdc++ -static-libgcc ${CUSTOM_MINGW_LINK_FLAGS}" \
                -e APP_NAME="OneLifeServer.exe"
